version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

formats:
  - htmlzip

sphinx:
  builder: html
  configuration: doc/conf.py

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dev
