name: Release Conda Package

on:
  push:
    tags:
      - "v*.*.*" # This will match tags like v1.0.0, v2.1.3, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-version: latest
          conda-channels: conda-forge
          auto-activate-base: true
          activate-environment: ""

      - name: Install dependencies
        run: |
          conda install conda-build
          conda install anaconda-client

      - name: Build Conda package
        run: |
          conda build recipe --output-folder conda-bld

      - name: Upload package to Anaconda.org
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        shell: bash -l {0}
        run: |
          conda install anaconda-client
          anaconda upload conda-bld/**/pygsp2-*.tar.bz2
